applications:
  argo-apps:
    namespace: argo-cd
    revisionHistoryLimit: 2
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argocd-apps
      targetRevision: 2.0.2
      helm:
        releaseName: argocd-apps
        valueFiles:
        - $values/argocd-apps.values.yaml
    - repoURL: 'https://github.com/yarencheng/20251120_demo_argocd_argocd_apps.git'
      targetRevision: main
      ref: values
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:

      # Sync automatically if automated:{} is not empty
      automated:
        prune: false
        selfHeal: false

      syncOptions:
      - CreateNamespace=true
  argo-cd:
    namespace: argo-cd
    revisionHistoryLimit: 2
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 9.1.3
      helm:
        releaseName: argo-cd
        valueFiles:
        - $values/argo-cd.values.yaml
    - repoURL: 'https://github.com/yarencheng/20251120_demo_argocd_argocd_apps.git'
      targetRevision: main
      ref: values
    destination:
      server: https://kubernetes.default.svc
    syncPolicy:

      # Sync automatically if automated:{} is not empty
      automated:
        prune: false
        selfHeal: false
      syncOptions:
      - CreateNamespace=true

  # To demo manual sync
  redis-cluster:
    namespace: argo-cd
    revisionHistoryLimit: 2
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
    - repoURL: oci://registry-1.docker.io/bitnamicharts/redis-cluster
      path: .
      targetRevision: 13.0.4
      helm:
        releaseName: redis-cluster
        valueFiles:
        - $values/redis-cluster.values.yaml
    - repoURL: 'https://github.com/yarencheng/20251120_demo_argocd_argocd_apps.git'
      targetRevision: main
      ref: values
    destination:
      server: https://kubernetes.default.svc
      namespace: redis-cluster
    syncPolicy:

      # Sync automatically if automated:{} is not empty
      # automated:
      #   prune: false
      #   selfHeal: false

      syncOptions:
      - CreateNamespace=true